### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Wolfr** [takaaa220/export_figma_variables_to_css#1]
Hi @takaaa220 .

I grabbed your code and made a modification for myself to just return a JS object. 

<img width="554" alt="plugin-screenshot" src="https://github.com/takaaa220/export_figma_variables_to_css/assets/12690/65a8f0d3-e519-4147-837e-8e901e29f84d">

The code was nicely written, great job.

https://github.com/takaaa220/export_figma_variables_to_css/blob/9c82e1d5bbfd210c189fa140a1fcd0b5422ddb98/package.json#L11

I wondered what is the license for your code?

Thank you!

**Comment by takaaa220** [comment]
@Wolfr 
Thanks for creating the issue! I'll add license later

I'm just interested, how do you use a generated JS Object?

**Comment by takaaa220** [comment]
Added! https://github.com/takaaa220/export_figma_variables_to_css/commit/eccd9cb203cc1de0ece9d27cf37bddd394689298

**Comment by Wolfr** [comment]
@takaaa220 thank you.

For example, persona content in the design like name, age etc... and then use the same content in an implementation.

**Comment by takaaa220** [comment]
@Wolfr 
Got it, thanks for your reply!
